import { TopicMeta } from './types';

/**
 * DSA (Data Structures & Algorithms) topics catalog.
 * Each topic uses lazy-load thunks for code splitting.
 * Topics ordered: searching → two-pointer → sliding-window → sorting → linked-list → graph
 */
export const dsaTopics: TopicMeta[] = [
  {
    id: 'linear-search',
    title: 'Linear Search',
    subtitle: 'Sequential search through array',
    tags: ['searching', 'array', 'linear', 'brute-force'],
    difficulty: 'beginner',
    status: 'ready',
    loadConfig: () => import('../algorithms/linear-search').then(m => m.linearSearchConfig),
  },
  {
    id: 'binary-search',
    title: 'Binary Search',
    subtitle: 'Efficient search in sorted arrays',
    tags: ['searching', 'array', 'logarithmic', 'divide-conquer'],
    difficulty: 'beginner',
    status: 'ready',
    loadConfig: () => import('../algorithms/binary-search').then(m => m.binarySearchConfig),
  },
  {
    id: 'two-pointer',
    title: 'Two Pointer',
    subtitle: 'Container With Most Water',
    tags: ['array', 'two-pointer', 'optimization', 'greedy'],
    difficulty: 'intermediate',
    status: 'ready',
    loadConfig: () => import('../algorithms/two-pointer').then(m => m.twoPointerConfig),
  },
  {
    id: 'sliding-window',
    title: 'Sliding Window',
    subtitle: 'Maximum Sum Subarray',
    tags: ['array', 'sliding-window', 'prefix-sum', 'optimization'],
    difficulty: 'intermediate',
    status: 'ready',
    loadConfig: () => import('../algorithms/sliding-window').then(m => m.slidingWindowConfig),
  },
  {
    id: 'bubble-sort',
    title: 'Bubble Sort',
    subtitle: 'Simple comparison sorting',
    tags: ['sorting', 'comparison', 'n2', 'stable'],
    difficulty: 'beginner',
    status: 'ready',
    loadConfig: () => import('../algorithms/bubble-sort').then(m => m.bubbleSortConfig),
  },
  {
    id: 'selection-sort',
    title: 'Selection Sort',
    subtitle: 'Find minimum and sort',
    tags: ['sorting', 'comparison', 'n2', 'in-place'],
    difficulty: 'beginner',
    status: 'ready',
    loadConfig: () => import('../algorithms/selection-sort').then(m => m.selectionSortConfig),
  },
  {
    id: 'insertion-sort',
    title: 'Insertion Sort',
    subtitle: 'Build sorted array incrementally',
    tags: ['sorting', 'comparison', 'adaptive', 'stable', 'in-place'],
    difficulty: 'beginner',
    status: 'ready',
    loadConfig: () => import('../algorithms/insertion-sort').then(m => m.insertionSortConfig),
  },
  {
    id: 'reverse-linked-list',
    title: 'Reverse Linked List',
    subtitle: 'Iterative pointer rewiring',
    tags: ['linked-list', 'pointers', 'reversal', 'in-place'],
    difficulty: 'intermediate',
    status: 'ready',
    loadConfig: () => import('../algorithms/reverse-linked-list').then(m => m.reverseLinkedListConfig),
  },
  {
    id: 'merge-two-sorted-lists',
    title: 'Merge Two Sorted Lists',
    subtitle: 'Merge operation for sorting algorithms',
    tags: ['linked-list', 'merge', 'two-pointer'],
    difficulty: 'intermediate',
    status: 'ready',
    loadConfig: () => import('../algorithms/merge-two-sorted-lists').then(m => m.mergeTwoSortedListsConfig),
  },
  {
    id: 'floyd-cycle',
    title: "Floyd's Cycle Detection",
    subtitle: 'Detect cycle in linked list',
    tags: ['linked-list', 'cycle-detection', 'two-pointer', 'slow-fast'],
    difficulty: 'advanced',
    status: 'ready',
    loadConfig: () => import('../algorithms/floyd-cycle').then(m => m.floydCycleConfig),
  },
  {
    id: 'dfs',
    title: 'Depth-First Search (DFS)',
    subtitle: 'Graph traversal via stack',
    tags: ['graph', 'traversal', 'dfs', 'backtracking', 'recursion'],
    difficulty: 'intermediate',
    status: 'ready',
    loadConfig: () => import('../algorithms/dfs').then(m => m.dfsConfig),
  },
  {
    id: 'bfs',
    title: 'Breadth-First Search (BFS)',
    subtitle: 'Graph traversal via queue',
    tags: ['graph', 'traversal', 'bfs', 'shortest-path', 'level-order'],
    difficulty: 'intermediate',
    status: 'ready',
    loadConfig: () => import('../algorithms/bfs').then(m => m.bfsConfig),
  },
];
